// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rep_Crime._01_LawEnforcement.API.Database.Context;

#nullable disable

namespace Rep_Crime._01_LawEnforcement.API.Migrations
{
    [DbContext(typeof(LawEnforcementDbContext))]
    [Migration("20221024194843_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Rep_Crime._01_LawEnforcement.API.Models.AssignedCrimeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CrimeEventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LawEnforcementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LawEnforcementId");

                    b.ToTable("assignedCrimeEvents");
                });

            modelBuilder.Entity("Rep_Crime._01_LawEnforcement.API.Models.LawEnforcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicLawEnforcementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("lawEnforcements");
                });

            modelBuilder.Entity("Rep_Crime._01_LawEnforcement.API.Models.AssignedCrimeEvent", b =>
                {
                    b.HasOne("Rep_Crime._01_LawEnforcement.API.Models.LawEnforcement", null)
                        .WithMany("AssignedCrimeEvents")
                        .HasForeignKey("LawEnforcementId");
                });

            modelBuilder.Entity("Rep_Crime._01_LawEnforcement.API.Models.LawEnforcement", b =>
                {
                    b.Navigation("AssignedCrimeEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
